auth_app/urls.py
from django.urls import path

from .views import RegisterCreateView, SignInLoginView, SingOutLogoutView

app_name = 'auth_app'

urlpatterns = [
    path('register/', RegisterCreateView.as_view(), name='register'),
    path('login/', SignInLoginView.as_view(), name='login'),
    path('logout/', SingOutLogoutView.as_view(), name='logout'),
]

main_app/urls.py
from django.urls import path

from .views import CreateVideoView, VideoListView, VideoView, PlayerStreamView, UserVideoListView

app_name = 'main_app'

urlpatterns = [
    path('', VideoListView.as_view(), name='video_list'),
    path('user_video/', UserVideoListView.as_view(), name='user_video'),
    path('video/<int:video_pk>', VideoView.as_view(), name='video'),
    path('player/<int:video_pk>', PlayerStreamView.as_view(), name='player'),
    path('add/', CreateVideoView.as_view(), name='add_video')
]

video/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls', namespace='main_app')),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_app/models.py
from django.db import models

# Create your models here.

main_app/models.py
import datetime

from django.conf import settings
from django.db import models


def file_name(instance, filename):
    filename = f'{datetime.datetime.utcnow()}.mp4'
    return '/'.join(['videos', instance.author.username, filename])


class Video(models.Model):
    """Модель видео"""
    title = models.CharField('Заголовок', max_length=256)
    description = models.TextField('Описание')
    preview = models.ImageField('Превью')
    video = models.FileField('Видео', upload_to=file_name)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='Автор')
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

auth_app/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class VideoUserCreationForm(UserCreationForm):
    """Форма регистрации нового пользователя"""

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class VideoUserLoginForm(AuthenticationForm):
    """Форма входа в учетную запись пользователя"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

main_app/forms.py
import os

from mutagen.mp4 import MP4

from django import forms
from django.core.exceptions import ValidationError

from .models import Video


class VideoCreateForm(forms.ModelForm):
    """Форма для добавления видео"""
    class Meta:
        model = Video
        fields = ('title', 'description', 'video')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_video(self):
        file = self.cleaned_data.get('video', False)
        if file:
            if file.content_type not in ['video/mp4']:
                raise ValidationError("Файл должен быть типа MP4")
            if not os.path.splitext(file.name)[1] in ['.mp4']:
                raise ValidationError("У файла должно быть расширение mp4")
            if file.size > 200 * 1024 * 1024:
                raise ValidationError("Видео файл слишком большой ( > 200mb )")
            if int(MP4(file).info.length) > 180:
                raise ValidationError("Продолжительность видео не должна превышать 3 минуты")
            return file
        else:
            raise ValidationError("Невозможно прочитать загружаемый файл")

auth_app/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import VideoUserCreationForm, VideoUserLoginForm


class RegisterCreateView(CreateView):
    """Регистрация нового пользователя"""
    template_name = 'auth_app/register.html'
    form_class = VideoUserCreationForm
    success_url = reverse_lazy('auth_app:login')


class SignInLoginView(LoginView):
    """Вход в учетную запись пользователя"""
    authentication_form = VideoUserLoginForm
    template_name = 'auth_app/login.html'


class SingOutLogoutView(LogoutView):
    """Выход из учетной записи пользователя"""

main_app/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, ListView

from .forms import VideoCreateForm
from .models import Video
from .services import get_preview, stream_video


class CreateVideoView(LoginRequiredMixin, CreateView):
    """Добавление нового видео"""
    template_name = 'main_app/add_video.html'
    form_class = VideoCreateForm
    success_url = reverse_lazy('main_app:video_list')

    def post(self, request, *args, **kwargs):
        form = VideoCreateForm(request.POST, request.FILES)

        if form.is_valid():
            video = form.save(commit=False)
            video.author = request.user
            video.preview = os.path.join('previews', get_preview(form.cleaned_data.get('video').temporary_file_path()))
            video.save()
            return redirect(reverse('main_app:video_list'))
        return render(request, 'main_app/add_video.html', {'form': form})


class VideoListView(ListView):
    """Вывод списка видео"""
    model = Video


class UserVideoListView(LoginRequiredMixin, ListView):
    """Вывод видео пользователя"""

    def get_queryset(self):
        return Video.objects.filter(author=self.request.user)


class VideoView(View):
    """Страница просмотра видео"""
    def get(self, request, video_pk):
        video = get_object_or_404(Video, pk=video_pk)
        return render(request, 'main_app/video.html', {'video': video})


class PlayerStreamView(View):
    """Потоковое транслирование видео"""
    def get(self, request, video_pk):
        video = get_object_or_404(Video, pk=video_pk)
        return stream_video(request, video.video.url)

templates/auth_app/login.html
{% extends 'base.html' %}

{% block title %}
    Вход
{% endblock %}

{% block content %}

<div class="container login">


    <form action="{% url 'auth_app:login' %}" method="post">
        {% csrf_token %}

        {% if next %}
            {% if 'review' in next %}
            <h5 class="text-center mb-4">Для добавления отзыва необходимо авторизоваться</h5>
            {% else %}
            <input type="hidden" name="next" value="{{ next }}">
            {% endif %}
        {% endif %}

        {{ form.as_p }}

        <input type="submit" class="form-control mt-5 btn btn-secondary" value="Войти">
    </form>

    <button class="form-control mt-5 btn btn-light text-white">
        <a href="{% url 'auth_app:register' %}">Зарегистрироваться</a>
    </button>

</div>

{% endblock %}

templates/auth_app/register.html
{% extends 'base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
<div class="container login">
    <form method="post" action="{% url 'auth_app:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control mt-5 btn btn-secondary" value="Зарегистрироваться">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    {% endblock %}


    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

{% block navbar %}
<div class="container-fluid fixed-top p-0">

    <div class="container-fluid menu">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col m-auto p-0 d-flex justify-content-between">
                    <div class="col label m-auto p-0">
                        <span>Video</span>
                    </div>
                    <div class="col mx-0">
                        <a class="p-0" href="{% url 'main_app:add_video' %}"><span>Добавить видео</span></a>
                    </div>
                    <div class="col mx-0">
                        <a class="p-0" href="{% url 'main_app:video_list' %}"><span>Все видео</span></a>
                    </div>

                    {% if user.is_authenticated %}

                    <div class="col">
                        <a class="p-2" href="{% url 'auth_app:logout' %}">Выйти</a>
                    </div>
                    <div class="col">
                        <a class="p-2" href="{% url 'main_app:user_video' %}">Мои видео</a>
                    </div>

                    {% else %}

                    <div class="col">
                        <a class="p-2" href="{% url 'auth_app:login' %}">Войти</a>
                    </div>

                    {% endif %}


                    {% if user.is_superuser %}
                    <div class="col">
                        <a class="p-2" href="{% url 'admin:index' %}">Админка</a>
                    </div>
                    {% endif %}


                </div>


            </div>

        </div>

    </div>
</div>


</div>

{% endblock %}

<div class="content">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>

{% block footer %}
<footer class="footer">
    <div class="basement">
        <div class="container">
            <div class="years d-flex justify-content-between">
                <p><b>© 2021 ООО “Видео”.</b> Копирование запрещено</p>
                <p>Политика конфиденциальности</p>

            </div>
        </div>
    </div>


</footer>
{% endblock %}

{% block js %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}


</body>
</html>

templates/main_app/add_video.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Добавление видео
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="my-3 text-center">Добавление видео</h1>
    <form method="post" action="{% url 'main_app:add_video' %}" enctype="multipart/form-data" class="mb-5">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="form-control mt-5 btn btn-secondary" value="Сохранить">
    </form>
</div>
{% endblock %}

templates/main_app/video.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet"/>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
{% endblock %}

{% block title %}
Player
{% endblock %}

{% block content %}

<div class="title mb-3 row justify-content-center mt-5">
    <h3>{{ video.title | title }}</h3>
</div>
<div class="row justify-content-center">
    <video
            id="my-video"
            class="video-js"
            controls
            preload="auto"
            width="640"
            height="360"
            poster="{% get_media_prefix %}{{ video.preview }}"
            data-setup="{}"
    >
        <source src="{% url 'main_app:player' video.pk %}" type="video/mp4"/>
        <source src="{% url 'main_app:player' video.pk %}" type="video/webm"/>

        <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a
            web browser that
            <a href="https://videojs.com/html5-video-support/" target="_blank"
            >supports HTML5 video</a
            >
        </p>
    </video>
</div>
<div class="row justify-content-center mt-3">
    <p align="justify">{{ video.description }}</p>
</div>
{% if video.author %}
<div class="author my-3 row justify-content-center">
    автор: {{ video.author.username }}
</div>
{% endif %}


{% endblock %}

{% block js %}
<script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}

templates/main_app/video_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Главная | blog
{% endblock %}

{% block content %}

<div class="container">

    <div class="article row">

        {% for video in object_list %}

        <div class="col-sm-4">
            {% if video.author %}
            <div class="author my-3">
                автор: {{ video.author.username }}
            </div>
            {% endif %}

            <a href="{% url 'main_app:video' video.pk %}">
                <div class="title mb-3">
                    <p>{{ video.title }}</p>
                </div>
            </a>

            <a href="{% url 'main_app:video' video.pk %}">
                <div class="poster mb-4">
                    <img src="{% get_media_prefix %}{{ video.preview }}" alt="poster">
                </div>
            </a>

            <p align="justify">{{ video.description }}</p>

        </div>
        {% empty %}

        <h1 class="mt-5">К сожалению, на данный момент нет активного видео контента!</h1>

        {% endfor %}
    </div>

</div>

{% endblock %}